version: '3.8'
services:
    db:
        image: mongo
        container_name: mongodb-container
        ports:
            - '27017:27017'
        command: [--auth]
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
          MONGO_INITDB_DATABASE: keyauth
          MONGO_USERNAME: admin
          MONGO_PASSWORD: 123456
        volumes:
            - 
            - ~/data/mongo_data:/data/db
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
